"""nova baza za trgovinu

Revision ID: 5c001675fbb4
Revises: 
Create Date: 2026-05-19 16:53:34.186985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c001675fbb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brendovi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=50), nullable=False),
    sa.Column('drzava', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kategorije',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('korisnici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('velicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broj', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=False),
    sa.Column('cijena', sa.Float(), nullable=False),
    sa.Column('brend_id', sa.Integer(), nullable=False),
    sa.Column('kategorija_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brend_id'], ['brendovi.id'], ),
    sa.ForeignKeyConstraint(['kategorija_id'], ['kategorije.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikl_velicina',
    sa.Column('artikl_id', sa.Integer(), nullable=False),
    sa.Column('velicina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artikl_id'], ['artikli.id'], ),
    sa.ForeignKeyConstraint(['velicina_id'], ['velicine.id'], ),
    sa.PrimaryKeyConstraint('artikl_id', 'velicina_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artikl_velicina')
    op.drop_table('artikli')
    op.drop_table('velicine')
    op.drop_table('korisnici')
    op.drop_table('kategorije')
    op.drop_table('brendovi')
    # ### end Alembic commands ###
